### ISSUE TITLE
[Feature] 'composite' support

### ISSUE THREAD

**Issue by xaviergonz** [motiondivision/motionone#100]
**Is your feature request related to a problem? Please describe.**

It would be nice if the library supported the composite option, like the web animation API does.

**Describe the solution you'd like**

That composite 'add' and 'accumulate' (or at least 'add') was supported besides 'replace'.

Sometimes I have two animations play at the same time and they change the same property (x, y, opacity, etc). My current solution is having nodes stacked so both animations don't interfere too much with one another, but if the library were to support other composite modes then I'd not need several nodes for a same object.

**Comment by NCarson** [comment]
Looks like the only holdout left is iOS Safari according to https://caniuse.com/web-animation. It says Safari v15 supports composite modes, which was released in July of 2024.
