### ISSUE TITLE
[Bug] Custom ease function works differently on transform vs individual transforms

### ISSUE THREAD

**Issue by Froskk** [motiondivision/motionone#132]
**1. Describe the bug**

When using a custom easing function animating `transform` it does not respect the custom ease function.
It is however correctly applied to animations using individual transforms.

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/magical-nobel-z5vcx2?file=/src/index.js

**3. Steps to reproduce**

Refresh the page in codesandbox or make an edit to restart the animation

**6. Browser details**
Chrome 104 and FF 104

**Comment by mattgperry** [comment]
As per the docs

> If a browser doesn't yet support `linear()` and the value being animated is not an independent transform (`x`, `scale` etc), Motion One will fallback to `"ease"`.
