### ISSUE TITLE
[Bug] Timeline step with at and duration not working

### ISSUE THREAD

**Issue by pauologuerra** [motiondivision/motionone#136]
**1. Describe the bug**

Using the following code in which I am trying to make both timeline steps start at the same time but have the second one have twice the duration of the first one using **at** and **duration** is not working. I have tried using the **at** and **duration** parameters in different order but it hasn't helped.

`const item1= document.querySelector('.item-1')
const items2= document.querySelectorAll('.item-2')

const sequence = [
  [item1, {transform: ['translate(0, 100px)', 'translate(0, 0)']}, {duration: 1}],
  [items2, {opacity: [0, 1]}, {at: 0}, {duration: 2}]
  // [items2, {opacity: [0, 1]}, {duration: 2}, {at: 0}]
]

timeline(sequence);`

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codepen.io/offbeat-io/pen/VwxYjPj

**3. Steps to reproduce**

1. Go to ['https://codepen.io/offbeat-io/pen/VwxYjPj'](https://codepen.io/offbeat-io/pen/VwxYjPj)
2. See error

**4. Expected behavior**

Both timeline steps should start at the same time with the second step taking more time to finish than the first one.

**Comment by mattgperry** [comment]
`at` is an animation option

`{ at: 0, duration: 2 }`

or 

`{ at: "<", duration: 2 }`
