### ISSUE TITLE
[Feature] Improve Vue docs

### ISSUE THREAD

**Issue by itpropro** [motiondivision/motionone#137]
The Vue docs have no examples for composition API usage, which is the recommended way to write Vue 3 applications. It would be great to have some examples how to use motionone with composition API and `<script setup lang="ts">` syntax.

**Comment by mattgperry** [comment]
I'm not a huge Vue user - as a component, does it make much of a difference between the composition API and how we've got it set up on the site?

**Comment by itpropro** [comment]
The examples are already using `setup` syntax, the difference is not that big, I can create a PR that adds docs examples for `script setup` if that is fine for you.

**Comment by mattgperry** [comment]
This is now a `wontfix`, see https://github.com/motiondivision/motionone/discussions/241

Hopefully future maintainers will have more time to take a look at this one!
