### ISSUE TITLE
[Bug] Smooth transition to {height: 'auto'}

### ISSUE THREAD

**Issue by mooxl** [motiondivision/motionone#139]
First of all, thank you for this beautiful animation library!

I just tried to port a navigation menu from React to Solid, which uses Motion (Framer) in the React version and an animation from {height: '0px') to {height: 'auto'} works as expected. 
Now that I use Motion for Solid in the new component, this transition is unfortunately no longer animated.

Here is a code sandbox to reproduce: https://codesandbox.io/s/transition-to-auto-f2nyfs?file=/App.tsx

Tested on the newes Version of Edge, Firefox and Safari on Monterey 12.5.1

**Comment by mattgperry** [comment]
Hey @mooxl! Although similar APIs, there's no expected feature parity between Framer Motion and the Motion One Solid/Vue apis. Browsers don't normally support this so Framer Motion does some "stuff" to support this feature that I probably won't be bringing over here. If I received a PR that added the functionality in a lightweight enough manner I'd consider putting it in but I'm closing this for now.
