### ISSUE TITLE
Motion One Performance Issue [Feature] [DevTools]

### ISSUE THREAD

**Issue by kevinseabourne** [motiondivision/motionone#142]
I loaded a basic solid js app. And used the motion one library to animate on mount some text. This text fades in and up. Before I added the library I ran a lighthouse test and the performance was 100%. As it should be, the page loads with only 1 title element. But after adding the library, implementing the animation fade in. I ran the test and the performance for the page from page dropped to 60%. I understand you will take a performance hit with spring based animation libraries but surely this can't be right ?

Is there anyway to have motion one load on a different thread using partytown ? Would this avoid bottleneck with the Javascript main thread ?

**Comment by mattgperry** [comment]
What precisely is it complaining about?

**Comment by mattgperry** [comment]
Ah that’s interesting. Most of the Solid stuff was external contribution so I’m not too knowledgable about solid and perf etc but it looks like there’s a lot of extra imports where Motion One doesn’t really have external deps. But we do import extra stuff from Solid. Is this page being packaged properly? It strikes me like this could be a dev environment

**Comment by kevinseabourne** [comment]
<img width="1121" alt="Screen Shot 2022-09-22 at 12 40 27 am" src="https://user-images.githubusercontent.com/29522030/191562521-2437309a-1791-41bc-b2f4-ce74b055cb6c.png">

This solid app is using the template provided on the solid js website.


<img width="587" alt="Screen Shot 2022-09-22 at 12 37 43 am" src="https://user-images.githubusercontent.com/29522030/191561999-8d65f113-4211-44f3-81e9-6242eb7f9425.png">

The test was run in dev environment.

**Comment by mattgperry** [comment]
Ah ok. It’s not really a relevant test then - dev has no bearing on the performance of a packaged site in bundlesize, runtime or asset quantity. I’m going to close for now but please reopen if you still find the same running against a deployed website.
