### ISSUE TITLE
[Bug] Animation played twice in Firefox

### ISSUE THREAD

**Issue by rootEnginear** [motiondivision/motionone#144]
**1. Describe the bug**

Animation played twice in Firefox **when**:
- That element has the animated property. Eg: you animate `opacity` property and the element's style also has `opacity` property.
- That animated property has `transition` property. Eg: `transition: opacity 1s`

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

<https://codesandbox.io/s/loving-http-jizb9i?file=/src/index.js>

**3. Steps to reproduce**

1. Make a `div` that has the style `div {opacity: 0; transition: opacity 1s}`
2. Animate that `div`: `animate("div", {opacity: [0,1]})`
3. Open in Firefox.
4. After finishing the first fade animation, it will play again.

**4. Expected behavior**

It should not play twice. MS Edge (Chromium) does not have this problem (might need a check on Safari).

**5. Video or screenshots**

https://user-images.githubusercontent.com/7108662/193212616-b5d2025d-bb64-4d94-9112-01d36e4664c5.mp4

**6. Browser details**

- Windows 10 Pro 21H2 build 19044.2006
- Firefox 105.0.1 (64 bit)
- MS Edge 105.0.1343.53 (Official build) (64-bit)

**Comment by rootEnginear** [comment]
I really appreciate you taking the time to respond. Thank you for your explanation.

**Comment by ElusiveByte** [comment]
Just had this problem. As stated by @mattgperry setting the transition to none on the problematic element completely fixed it. Thanks!
