### ISSUE TITLE
[Bug] Linear Gradient on backgroundImage

### ISSUE THREAD

**Issue by prests** [motiondivision/motionone#151]
**1. Describe the bug**

Motion one is not animating the linear gradient properly on a `backgroundImage` property

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codepen.io/shayne1202/pen/jOxJvRV

**3. Steps to reproduce**

**4. Expected behavior**

I was hoping the percentages would grow/shrink gradually, but there is only an abrupt change at the end of the animation duration.

**5. Video or screenshots**

**6. Browser details**

**Comment by stepanjakl** [comment]
Hi, I was just facing a similar issue. Here is what I did - using the `progress` param to interpolate the gradient percentage: https://codepen.io/stepj/pen/Rwyzzwz

**Comment by mattgperry** [comment]
Yeah the progress approach to write your own interpolation is the best way. We're not going to explicitly write this in because this is something browsers don't support natively and adding our own interpolation would significantly increase bundlesize.
