### ISSUE TITLE
[Bug] Animations on element like hover, press and animate, don't recognise Animate function animations with CSS in JS Library

### ISSUE THREAD

**Issue by kevinseabourne** [motiondivision/motionone#152]
🐛 Bug  
when using a css in js library motion one does not recognise animations from the class based animate function. If you use hover over an element and you have animated the element using animate for example x: 20 on mount. When you hover over the element, it reverts back to x: 0 then you can  hover over it and the animation will work. It didn't recognise animate had moved the elements position.

Also the delay in hover does not override animate delay. For example if a transition is set to deiay 0.5s and I set a delay for hover to be 0. If I hover the element still has a 0.5s delay. 

Here is a working example of what Im talking about, Try hover.
https://stackblitz.com/edit/solidjs-templates-ywdyd1?ctl=1&embed=1&file=src/App.tsx
  
It would also be great to use stagger inside a transition property on the element instead of outside with the animate function and having to refer to the element with a class name. And stagger with spring

![MEME](https://user-images.githubusercontent.com/29522030/197318587-2c23bb71-dc14-4ab2-9a2b-b07a36489a2c.jpeg)

I have been trying to use motion one in a solidjs and I thought it wasn't supported because I was declaring motion like you do in framer motion `styled(motion.button)` 

But I found this works if anyone is trying to use motion one with a css in js library declare your styles like so.

 ```javascript
 const Btn = styled(Motion.button)`
 
 `
 ``` 
 
 Perhaps an update to docs explaining use with css in js libraries ?

**Comment by mattgperry** [comment]
This is now a `wontfix`, see https://github.com/motiondivision/motionone/discussions/241

Hopefully future maintainers will have more time to take a look at this one!
