### ISSUE TITLE
Please add docs search

### ISSUE THREAD

**Issue by kouliavtsev** [motiondivision/motionone#158]
**Is your feature request related to a problem? Please describe.**
I am checking someone else's code and trying to understand what this function does:

```js
import { wrap } from "@motionone/utils";
const x = useTransform(baseX, (v) => `${wrap(-20, -45, v)}%`);
```

It seems that utils are not documented, yet I still have to click through the docs to ensure I missed something. 

**Describe the solution you'd like**
A search function like Agnolia would same a lot of time.

**Comment by mattgperry** [comment]
I'm currently porting the docs to Framer, once complete this will have search functionality.

**Comment by MiguelSilvaViana** [comment]
https://www.framer.com/motion/scroll-animations/
https://codesandbox.io/p/sandbox/framer-motion-scroll-velocity-r1dy4u?file=%2Fsrc%2FApp.tsx%3A6%2C13

the docs are probably outdated, I'm trying to follow the docs but in the framer-motion version: "^11.0.3", and I have the same problem saying it doesn't exist: import { wrap } from '@motionone/utils'; Do we need to install the part? Or has this function been discontinued?
