### ISSUE TITLE
[Bug] MotionOne for Solid - Events not being fired

### ISSUE THREAD

**Issue by sumberacstefano** [motiondivision/motionone#161]
**1. Describe the bug**

When reading the documentation about Motion One for Solid you get provided with events that emit on rendered element.

`onViewEnter` and `onViewLeave` events are not being logged in console.
`onPressStart` and `onPressEnd` events are not being logged in console.
`onHoverStart` and `onHoverEnd` events are not being logged in console.

**2. Steps to reproduce**

1. Wrap an element with: 
```
<Motion onViewEnter={({ detail }) => console.log("Start: ", detail)} onViewLeave={({ detail }) => console.log("Start: ", detail)}>
  <p>Your Element</p>
</Motion>
```
2. Open console
3. Nothing happens when element is in viewport

**3. Expected behavior**

Events should be fired and logged inside the console.

**Comment by feledori** [comment]
Yeah just noticed this as well. inView etc does not work. Currently trying to find the bug.

**Comment by cakir-enes** [comment]
any updates on this?

**Comment by mattgperry** [comment]
Yeah you're right @feledori, I actually didn't have much of a hand in the Solid implementation but will accept PRs for sure

**Comment by SilentRhetoric** [comment]
May I ask if there are any plans to fix this issue?

**Comment by mattgperry** [comment]
This is now a `wontfix`, see https://github.com/motiondivision/motionone/discussions/241

Hopefully future maintainers will have more time to take a look at this one!
