### ISSUE TITLE
[Feature] Add onExitComplete to Presence component in solid-js

### ISSUE THREAD

**Issue by oSethoum** [motiondivision/motionone#181]
**Is your feature request related to a problem? Please describe.**
the `Presence` component doesn't have an `onExitComplete` callback props

**Describe the solution you'd like**
a way to add callback when the animation the exit transition finishes.

**Comment by oSethoum** [comment]
@mattgperry can this be added?

**Comment by Nmans01** [comment]
+1 This would be useful for a SolidJS project I am working on. I want to be able to animate exits for items that are being deleted, and I want to be able to trigger the true deletion of an item after its animation has been completed.

**Comment by thetarnav** [comment]
This should be very easy to add.
As a workaround you probably can listen to `motioncomplete` on parent element and rely on event bubbling up.

**Comment by mattgperry** [comment]
This is now a wontfix, see https://github.com/motiondivision/motionone/discussions/241

Hopefully future maintainers will have more time to take a look at this one!
