### ISSUE TITLE
[Bug] Trying to support Motion One through purchasing dev tools leads to sign in error page 

### ISSUE THREAD

**Issue by RADreymann** [motiondivision/motionone#184]
"Try signing in with a different account." regardless of Browser

**Comment by ChrisGV04** [comment]
I'm also getting the same error when trying to purchase Motion One Pro

**Comment by tsoruu** [comment]
Getting the same error here, going incognito (to disable all extensions and cache) produce the same error...

**Comment by JamesManningR** [comment]
Getting the same error. Given that the dev tools are public, has the purchase been disabled since it's free now anyway?@mattgperry

**Comment by JamesManningR** [comment]
> Yes that’s right - I haven’t had the time I would have liked to support it so I’ve ended subs/closed purchases and made it free

Thank you for the clarification! 

Is there another way we could do about supporting the project?

**Comment by mattgperry** [comment]
No it's all good, thanks!
