### ISSUE TITLE
[Feature]What unique footprints can tell if a website is using Motion One technology?

### ISSUE THREAD

**Issue by ceopeo** [motiondivision/motionone#195]
**Is your feature request related to a problem? Please describe.**
I want to know if it is possible to analyze the source code of the page to determine whether the Motion One technology is used

**Comment by mattgperry** [comment]
I don't think there's a great way of finding this out. Two tell-tale signs:

- Transform string contains values like `var(--motion-x)`
- style attribute doesn't change during animation but once animation is complete, final value is applied
