### ISSUE TITLE
[Bug] SolidJS type error with vite@latest

### ISSUE THREAD

**Issue by jaekwak02** [motiondivision/motionone#207]
**1. Describe the bug**

I am getting this type error when I import anything from @motionone/solid.

```
Could not find a declaration file for module '@motionone/solid'. '/Users/jae/Documents/code/motionone-bug-test/node_modules/@motionone/solid/dist/esm/index.js' implicitly has an 'any' type.

There are types at '/Users/jae/Documents/code/motionone-bug-test/node_modules/@motionone/solid/dist/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@motionone/solid' library may need to update its package.json or typings.ts(7016)
```

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Sorry, I can't reproduce it there.

**3. Steps to reproduce**

1. yarn create vite@latest and choose Solid + Typescript
2. install @motionone/solid
3. import anything from @motionone/solid
4. Error appears

**6. Browser details**

```
MacOS 12.6.3
"@motionone/solid": "^10.16.2",
"solid-js": "^1.7.8"
```

**Comment by cs-clarence** [comment]
still not fixed as of `@motionone/solid@10.16.4`

**Comment by chaozwn** [comment]
> still not fixed as of `@motionone/solid@10.16.4`

same problems.

**Comment by c-ehrlich** [comment]
Doesn't seem to be vite specific - I get the same issue using `@motionone/solid@10.16.4` in Astro.

**Comment by Walidoux** [comment]
same here on a vite tauri app

**Comment by KFeu1** [comment]
I was able to fix it by adding this to my tsconfig.json

```ts
{
  "compilerOptions": {
    "paths": {
      "@motionone/solid": ["./node_modules/@motionone/solid/dist/types/index.d.ts"]
    }
  }
}
```

**Comment by mattgperry** [comment]
This is now a `wontfix`, see https://github.com/motiondivision/motionone/discussions/241

Hopefully future maintainers will have more time to take a look at this one!
