### ISSUE TITLE
[Bug] Inview not getting triggered when the targed is an svg path

### ISSUE THREAD

**Issue by Ladvace** [motiondivision/motionone#215]
**1. Describe the bug**

Basically when you try to target a `path` tag using the inView function, it doesn't work, but it works for other elements

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/pensive-marco-7cp3vs

**Comment by mattgperry** [comment]
I believe this is a browser limitation with the `IntersectionObserver`
