### ISSUE TITLE
[Bug] SolidJS Presence animation configured using reactive nullable value raises stale value error

### ISSUE THREAD

**Issue by hadar759** [motiondivision/motionone#219]
**1. Describe the bug**

When using `Presence` in SolidJS, configuring styles in the `animate` field using a reactive variable which results in a nullish value leads to a stale value error.

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/stale-value-using-presence-dps2gg?file=/App.tsx

**3. Steps to reproduce**

1. Go to the CodeSandbox reproduction
2. Click on "Set value to undefined"
3. See error

**4. Expected behavior**

Animation keeps using the last value provided, or animation completely stops.

**5. Video or screenshots**

https://github.com/motiondivision/motionone/assets/23258552/740dd111-18c6-4708-b002-e8050b294f86

**6. Browser details**

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          |     Arc Version 1.6.0 (41215) Chromium Engine Version 116.0.5845.140       |
| Operating System |     MacOS Ventura 13.3.1     |

**Comment by mattgperry** [comment]
This is now a `wontfix`, see https://github.com/motiondivision/motionone/discussions/241

Hopefully future maintainers will have more time to take a look at this one!
