### ISSUE TITLE
[Bug] TypeError: Failed to execute 'animate' on 'Element': duration must be non-negative or auto 

### ISSUE THREAD

**Issue by Ladvace** [motiondivision/motionone#222]
**1. Describe the bug**
I have a timeline and I'm trying to start an animation along another assigning a `name` and using it in the `at` property as below, but when I do that I get the error in that title

```  
     [
        "#inner-column-container",
        { height: ["350%", "100%"] },
        { easing: "ease-in-out", duration: "2.5", name: "initial-scale" },
      ],
      [
        "#animation-container",
        { scale: ["0.1", "1"] },
        { easing: "ease-in-out", at: "initial-scale", duration: "2" },
      ]
```

error:

`[Bug] TypeError: Failed to execute 'animate' on 'Element': duration must be non-negative or auto `

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[Reproducible example](https://codesandbox.io/p/github/Ladvace/qwik-portfolio-photography/master?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clmdpi55v000j3b6wu61oe7nl%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clmdpi55v000e3b6wdrtovfya%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clmdpi55v000i3b6wuuqnlutq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clmdpi55v000g3b6wmq6mcf3c%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clmdpi55v000e3b6wdrtovfya%2522%253A%257B%2522id%2522%253A%2522clmdpi55v000e3b6wdrtovfya%2522%252C%2522activeTabId%2522%253A%2522clmdpjnm500sh3b6wsxrrpte1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clmdpi55v000d3b6wsxygzdj6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Froutes%252Findex.tsx%2522%252C%2522id%2522%253A%2522clmdpjnm500sh3b6wsxrrpte1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clmdpi55v000g3b6wmq6mcf3c%2522%253A%257B%2522id%2522%253A%2522clmdpi55v000g3b6wmq6mcf3c%2522%252C%2522activeTabId%2522%253A%2522clmdpijoq00m63b6wbvj3rdnn%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clmdpijoq00m63b6wbvj3rdnn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clmdpi55v000i3b6wuuqnlutq%2522%253A%257B%2522id%2522%253A%2522clmdpi55v000i3b6wuuqnlutq%2522%252C%2522activeTabId%2522%253A%2522clmdpifas00ik3b6w4xk63ap2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clmdpi55v000h3b6wo7syi86i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clmdpi5a3001ce6fzdqk46n07%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clmdpifas00ik3b6w4xk63ap2%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by mattgperry** [comment]
Can you reopen with a minimal reproduction? This sandbox is broken for me and just a simple timeline that reproduces this would be helpful.
