### ISSUE TITLE
Typo fix and suggested improvements in scroll docs

### ISSUE THREAD

**Issue by Acccent** [motiondivision/motionone#228]
I found the [documentation page for scroll](https://motion.dev/dom/scroll), specifically the explanation about offset, to be quite confusing. Additionally there is a typo in one of the examples. I wanted to submit a PR but I can't find the repo for the docs, maybe there isn't one.

- ## Typo

Under **[Predefined offsets](https://motion.dev/dom/scroll#predefined-offsets)**:
> [...]
> For instance, here's an animation that will fade an element out as it leaves the start/end of the viewport:
> 
> ```js
> scroll(animate(element, { opacity: [0, 1, 1, 0] }), {
>   target: element,
>   offsets: [...ScrollOffset.Enter, ...ScrollOffset.Exit],
> })
> ```
The "offsets" property should be **offset** (no s).

- ## Suggested improvements

This is the current explanation for the offsets:
> ### Scroll offsets
> Notice also how in the previous example we've set the offset option. This allows us to define exactly which intersections between target and container we want to consider the start and end of the animation.
> 
> A each intersection is defined where the target will meet the container. So for example, "start end" means when the start of the target meets the end of the container.

I found this really unclear personally, especially because it doesn't mention the scroll direction and only talks about the animation's start and end – when in a later example 4 offsets are given (so it's unclear what the extra 2 are for). It only really clicked when I realized this "offset" property was essentially an equivalent of `animate`'s keyframe offsets. I think this should be made explicit. Here's a suggested rewrite:

> ### Scroll offsets
> Notice also how in the previous example we've set the offset option.
> Just like [timing offsets](https://motion.dev/dom/animate#custom-keyframe-timing) map animation keyframes to the animation's _timing_, **scroll offsets** map keyframes to the _scroll state_ of the target element relative to its container. This allows us to define how the animation progresses as the element scrolls into the container from the bottom, then out from the top.
> 
> Each offset comprises two values: a point in the target element, and a point in the container element. For example, "start end" means "the start (top) of the target, and the end (bottom) of the container". Together, these two values represent the moment when those two points intersect; so, in the above example, the moment when the start of the target meets the end of the container.
>
> Therefore, an offset property of `["start end", "end end"]` means the animation will reach its first keyframe when the target begins entering into view (the target's start meets the container's end); and, as the user scrolls, the animation will reach its second keyframe when the target is fully inside the container (the target's end meets the container's).
>
> More offsets can be added to match animations with more than two keyframes. If there are more keyframes than offests, \<default behavior should be explained here\>.

**Comment by mattgperry** [comment]
Thanks for the suggestion, deploying some copy updates now!
