### ISSUE TITLE
[Bug] Error on website `/App.tsx: _standard is not defined (2:0)`

### ISSUE THREAD

**Issue by danieltroger** [motiondivision/motionone#232]
**1. Describe the bug**

On https://motion.dev/solid/quick-start#exit-animations the example seems to fail

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Go to https://motion.dev/solid/quick-start#exit-animations

**3. Steps to reproduce**

1. Go to website
2. See red text

**4. Expected behavior**

No red text, shows example

**5. Video or screenshots**

<img width="1052" alt="Screenshot 2023-10-17 at 09 30 41" src="https://github.com/motiondivision/motionone/assets/4047180/1137c080-dc25-487a-ae8a-07ce4249579b">

**6. Browser details**

Firefox 119.0b9 (64-bit) on macOS 14.0 (23A344)

**Comment by mattgperry** [comment]
This is now a `wontfix`, see https://github.com/motiondivision/motionone/discussions/241

Hopefully future maintainers will have more time to take a look at this one!
