### ISSUE TITLE
[Bug] Forward filling animation not working in Shadow DOM

### ISSUE THREAD

**Issue by bakura10** [motiondivision/motionone#234]
Hi :),

I have found a bug that I am unable to fix. When doing an animation for an element inside a Shadow DOM, the forward-filling mechanism of Motion does not seem to work (wether I use animation or timeline).

Motion properly set the style properties when animation end, but for some strange reason, it seems that the original style are always "winning" over the inline styles set up by Motion.

You can find a reproduction case here: https://codepen.io/bakura10/pen/poGyBRj

Thanks.

EDIT: I have tried to use native JS animation and the problem is the same, so the issue is not due to Motion I think. Interestingly enough, when using native API directly, using `fill: 'both'` does the trick, but as Motion does not expose the fill property, this can't be used.

**Comment by bakura10** [comment]
I reported this to Chrome team and, apparently, this is the expected result as per spec. Although it is completely unpredictable (https://bugs.chromium.org/p/chromium/issues/detail?id=1497897#c6).

I wonder if Motion could handle that by making the styles !important when the animation is over when it detects it is in a shadow root context (which can be done by using `element.getRootNode()` and detecting if it is a shadow root).

@mattgperry do you think making important here would cause other issues?

**Comment by mattgperry** [comment]
Sadly you can't set `!important` via the `style` attribute and I don't want to get into the murky world of creating CSS blocks. That spec'd behaviour seems really unhelpful though. `fill` is actually set to `both` but the animation is ended when the styles are applied. We have an undocumented option called `persist` which can be set to `true` - you could attempt this? But this behaviour makes interrupting animations difficult/impossible.
