### ISSUE TITLE
[Feature] POJO support

### ISSUE THREAD

**Issue by FractalHQ** [motiondivision/motionone#235]
**Is your feature request related to a problem? Please describe.**
This library has everything I need from an animation library besides one thing -- the ability to animate any object as opposed to only DOM elements.  Being able to throw a random class instance or threejs `Object3D` at a sequence would be huge.

**Describe the solution you'd like**
Objects just work, à la GSAP

**Comment by ShanonJackson** [comment]
```
let obj = {progress: 0}
animate((progress) => obj.progress = progress, { duration: 0.5 });
```

**Comment by FractalHQ** [comment]
@ShanonJackson Thanks, I heard about using functions in a thread somewhere but couldn't find that in the docs.

That API isn't quite as nice and, I'd imagine, wouldn't scale nicely either with very large, complex systems.  Nonetheless, it's much better than nothing.

I'm curious about your example though -- did you mean to destructure `progress` in the callback? i.e.:

```ts
let obj = {progress: 0}
animate(({ progress }) => obj.progress = progress, { duration: 0.5 });
```

If so, that makes sense.  If not, I've got a few more questions 😅
