### ISSUE TITLE
v10.17.0 was published without child packages being updated

### ISSUE THREAD

**Issue by joneath** [motiondivision/motionone#243]
**1. Describe the bug**

When v10.17.0 was released on NPM the dependent framework packages weren't released which results in an import error due to missing dependencies.

```
 ERROR  Pre-transform error: Failed to resolve import "@motionone/vue" from
```

**3. Steps to reproduce**

1. Install v10.7.0 in a framework specific project (Vue in my case)
2. Try and import from the `@motionone/vue` package
3. See error

**4. Expected behavior**

Child packages to be released with the parent package

**Comment by mattgperry** [comment]
That’s odd - this package has been deprecated (see docs for upgrade paths). I can’t see any remaining references to it. Can I see the versions in your package.json?

**Comment by everyx** [comment]
@joneath  You can install [@motionone/vue] separately (https://www.npmjs.com/package/@motionone/vue?activeTab=readme)

**Comment by joneath** [comment]
Ah, I hadn't realized that. If anyone hit's this issue with Vue/Nuxt, the project has moved to @oku-ui/motion-nuxt and is a drop-in replacement. Closing now. Thanks @mattgperry
