### ISSUE TITLE
is motion-one dead?

### ISSUE THREAD

**Issue by LazyClicks** [motiondivision/motionone#246]
sorry to ask this but the project seems to receive little to no updates?
and the social account has been inactive for a year now

**Comment by LazyClicks** [comment]
alright thank you @mattgperry

**Comment by nam-co** [comment]
Just a note, after this @mattgperry updated the motion one site and library

**Comment by LazyClicks** [comment]
> Just a note, after this @mattgperry updated the motion one site and library
yes i noticed a set of small updates after the blog was posted
