### ISSUE TITLE
[Feature] inView initial value

### ISSUE THREAD

**Issue by justijndepover** [motiondivision/motionone#247]
I'm using the `inView` method to have my text fade in from the left. I am also using a margin so the animation is more visible to the end user.

```js
inView('[data-fade-left]', ({ target }) => {
    animate(target, {
        translateX: ['-100px', 0],
        opacity: [0, 1],
    }, {
        duration: .4,
        delay: .1
    });
}, { margin: "-100px 0px -100px 0px" });
```

However, when I scroll down and the element is within the screen, but not within the margin box, It's visible at its original position.
When the element scrolls within the 100px offset, the element snaps to the left, becomes translucent and then the animation starts.

I have solved this right now by also setting the initial values in css (`opacity: 0` and `transform: translateX(-100px)`).

It would be nice if the start value is already applied by the library, even though the element is not within view.

**Comment by f-elix** [comment]
You can call `animate` outside of `inView` with `autoplay: false`, then use the returned controls to play the animation inside `inView`.

```ts
const animation = animate(target, {
        translateX: ['-100px', 0],
        opacity: [0, 1],
    }, {
        duration: .4,
        delay: .1,
        autoplay: false
    });
    
inView('[data-fade-left]', ({ target }) => {
    animation.play();
}, { margin: "-100px 0px -100px 0px" });
```

This will apply the initial animation styles to the target without playing the animation.

**Comment by IgorSzymanski** [comment]
```
animation.play();
```

@f-elix That will replay the animation with all selected elements each time a `[data-fade-left]` element appears in view. I don't think that's what OP needed.

**Comment by justijndepover** [comment]
Indeed, I just stuck with setting the initial values through css

**Comment by f-elix** [comment]
@IgorSzymanski No, if you want to play the animation every time the element appears, you have to return a callback from the function.

```ts
inView('[data-fade-left]', ({ target }) => {
    animation.play();
    return () => {
      // ...
    }
}, { margin: "-100px 0px -100px 0px" });
```

If you don't return this, the function will only be called once, hence the animation will only be played once.

As for @justijndepover, this is exactly what my example does. When you call `animate()` with `autoplay: false`, the initial animation styles are applied on the elements so you don't have to set them through css. Since the animation is not played immediately, you can then call `animation.play()` in the `inView` callback.

**Comment by justijndepover** [comment]
Say you have the following html:

```html
<div data-fade-left>
    <p>element 1</p>
</div>
<div data-fade-left>
    <p>element 2</p>
</div>
```

If you scroll just a little until the first element is in the viewport, the animation will work just fine. (Also with the initial values set like I asked for).

If you scroll further until the second element is in the viewport, the animation will re-run but on both elements, not just on the second.

**Comment by justijndepover** [comment]
I actually don't mind setting the initial value through CSS because that prevents layout shifting if the element is in the initial viewport and JS has not run yet.
I'll close the ticket since I don't have a need for this request anymore but feel free to discuss further.

**Comment by f-elix** [comment]
Oh you're right, sorry I missed that! 

In that case, I guess you could call `animate()` with `autoplay: false`, then call `animate()` again with the same config inside the `inView` callback. A bit hacky but it should work.
