### ISSUE TITLE
[BUG] Animation isn't triggered first time toggling Motion component in Vue

### ISSUE THREAD

**Issue by Healios** [motiondivision/motionone#53]
**1. Describe the bug**

The first time the variable controlling v-show on the Motion component changes, the specified animation doesn't trigger. It is only on subsequent value changes of the variable that the animation triggers.

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/first-animation-doesnt-work-5vv8z6

**3. Steps to reproduce**

1. Click "toggle". You should see the box appear **without** an animation.
2. Click "toggle". You should see the box disappear **with** an animation.
3. Click "toggle". You should see the box appear **with** an animation.

**4. Expected behavior**

I expect the box to appear with an animation the first time I press the "toggle" button.

**5. Video or screenshots**

![bug](https://user-images.githubusercontent.com/9387114/154866574-89507ed1-f061-4fb3-b259-baaa907f1ab4.gif)

**6. Browser details**

Bug occurs when using Windows 10 & 11 and when using Brave (Chromium) and FireFox.

**Comment by tobatha** [comment]
Jesus christ, i just filed the same bug, and saw this.... LOL, #194

**Comment by mattgperry** [comment]
This is now a `wontfix`, see https://github.com/motiondivision/motionone/discussions/241

Hopefully future maintainers will have more time to take a look at this one!
