### ISSUE TITLE
Pseudo element support

### ISSUE THREAD

**Issue by tinleym** [motiondivision/motionone#54]
**Is your feature request related to a problem? Please describe.**
It would be nice to target pseudo elements

**Describe the solution you'd like**
This article describes the native implementation: https://danielcwilson.com/blog/2020/05/pseudo-waapi/

**Comment by bakura10** [comment]
I came across the need for supporting pseudo element animation, specifically to animate backdrop for dialog with a timeframe. Is it still something that is not possible despite the recent remove of polyfill for Safari?
