### ISSUE TITLE
[BUG] Cannot find module '/sandbox/node_modules/@motionone/vue/dist/motion-vue.cjs.js'. Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by dprbook** [motiondivision/motionone#55]
**1. Describe the bug**

Environment: Vue 3, Vite, and Vitest (https://github.com/vitest-dev/vitest).
Importing the library in a component works fine, when using vite, but when imported using vitest, it throws an error (see sandbox).

**2. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/icy-sky-kin15v?file=/README.md:29-97

**3. Steps to reproduce**

1. Toggle in browser -> works fine
2. Second terminal
   a) yarn test -> error
   b) mv ./node_modules/@motionone/vue/dist/motion-vue.ssr.js ./node_modules/@motionone/vue/dist/motion-vue.cjs.js
   c) yarn test -> works
3. Reload of dev server -> still works

**4. Expected behavior**

Importing the library using vitest works as well. 

**5. Analysis**

Executing the project normally with "yarn dev" works fine, but running the test with "yarn test" throws an error.
The file "dist/motion-vue.cjs.js" referenced in @motionone/vue/package.json#7 does not exist.

Two fixes I found:
1. renaming the file "dist/motion-vue.ssr.js" to the value above or 
2. changing line 7 of the package.json to "dist/motion-vue.ssr.js" both do the trick.
The execution of the vite dev server is unaffected.

Seems to me, the bug at a mismatch between the aforementioned package.json and the rollup build config at vue/rollup.config.js#126, where the output file of the build command for the cjs-format is set to the ssr.js-version of the file name, but in the package.json it is referenced as .cjs.js. Though I admit, I'm certainly no expert on the topic.

**Comment by shikhar0507** [comment]
Any updates on this fix ?

**Comment by mattgperry** [comment]
This is now a `wontfix`, see https://github.com/motiondivision/motionone/discussions/241

Hopefully future maintainers will have more time to take a look at this one!
